# Generated by Django 5.2.17 on 2026-09-22 15:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_preferred_supplier'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('RETURN', 'Return')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_type', models.CharField(max_length=40)),
                ('reference_id', models.PositiveBigIntegerField()),
                ('reference_code', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('receive_stock', 'Can receive stock')],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='catalog.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.stockreceipt')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='inventory.inventorytransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'warehouse', 'created_at'], name='inventory_i_product_ae8a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['warehouse', 'created_at'], name='inventory_i_warehou_7aee79_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='inventory_i_transac_1f1168_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_ace22e_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_change__gt', 0), ('quantity_change__lt', 0), _connector='OR'), name='inventorytransaction_quantity_nonzero'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['warehouse', 'product'], name='inventory_s_warehou_7c5a96_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_stock_product_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stocklevel_on_hand_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stocklevel_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stocklevel_reserved_lte_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='stockreceiptitem',
            constraint=models.UniqueConstraint(fields=('receipt', 'product'), name='unique_receipt_product'),
        ),
    ]
