# Generated by Django 5.2.17 on 2026-09-22 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_preferred_supplier'),
        ('inventory', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('transfer_stock', 'Can transfer stock')],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('FOUND', 'Found'), ('CORRECTION', 'Correction'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='catalog.product')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventorytransaction')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('adjust_stock', 'Can adjust stock')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change__gt', 0), ('quantity_change__lt', 0), _connector='OR'), name='stockadjustment_quantity_nonzero')],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='catalog.product')),
                ('transaction_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items_in', to='inventory.inventorytransaction')),
                ('transaction_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items_out', to='inventory.inventorytransaction')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.stocktransfer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transfer', 'product'), name='unique_transfer_product')],
            },
        ),
    ]
