# Generated by Django 5.2.17 on 2026-09-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reports', 'Can view reports'), ('export_reports', 'Can export reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
