# Generated by Django 5.2.17 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_preferred_supplier'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('PO_SUBMITTED', 'Purchase order submitted'), ('PO_APPROVED', 'Purchase order approved'), ('PO_RECEIVED', 'Purchase order received'), ('TRANSFER_COMPLETED', 'Transfer completed'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notificatio_recipie_da81fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW', 'Low'), ('OUT', 'Out')], max_length=8)),
                ('last_notified_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_alert_states', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_alert_states', to='warehouses.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse', 'alert_type'), name='unique_stock_alert_state')],
            },
        ),
    ]
